### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by davidbeechey**
@jpfbastos I'm just guessing that you might have `lib/motors` and `lib/levitation`, but we can always change it later if that's not right. @kshxtij let me know if I've missed anything from infra :)

### CODE REVIEW

**Review by arjunnaha — APPROVED** [review]
LGTM

**Review by kshxtij — APPROVED** [review]
Idk if boards counts as infra but probably? otherwise LGTM

**Review by misha7b — APPROVED** [review]

**Comment by jpfbastos** [comment]
> @jpfbastos I'm just guessing that you might have `lib/motors` and `lib/levitation`, but we can always change it later if that's not right. @kshxtij let me know if I've missed anything from infra :)

yeah that sounds good

**Review by jpfbastos — APPROVED** [review]
LGTM!

**Review by DylanCavers — APPROVED** [review]

**Review by licornes-fluos — APPROVED** [review]

**Review by H-Allen — APPROVED** [review]

**Pull request merged**
